### ISSUE TITLE
Apparent PHP incompat

### ISSUE THREAD

**Issue by gdude2002** [dokuwiki/docker#36]
Using `dokuwiki/dokuwiki:stable`, I get this error on all pages:

![Error: Found unconstructed IntlDateFormatter](https://github.com/user-attachments/assets/5847fcb3-8963-4137-9ac6-152451677881)

In the error logs:

```
2025-05-20 11:20:06     /var/www/html/vendor/php81_bc/strftime/src/IntlLocaleFormatter.php(73)  Error: Found unconstructed IntlDateFormatter
  #0 /var/www/html/vendor/php81_bc/strftime/src/IntlLocaleFormatter.php(73): IntlDateFormatter->format()
  #1 /var/www/html/vendor/php81_bc/strftime/src/php-8.1-strftime.php(144): PHP81_BC\strftime\IntlLocaleFormatter->__invoke()
  #2 [internal function]: PHP81_BC\{closure}()
  #3 /var/www/html/vendor/php81_bc/strftime/src/php-8.1-strftime.php(125): preg_replace_callback()
  #4 /var/www/html/inc/common.php(1471): PHP81_BC\strftime()
  #5 /var/www/html/inc/toolbar.php(277): dformat()
  #6 /var/www/html/inc/template.php(379): toolbar_signature()
  #7 /var/www/html/lib/tpl.core/dokuwiki/main.php(21): tpl_metaheaders()
  #8 /var/www/html/inc/actions.php(30): include('...')
  #9 /var/www/html/doku.php(131): act_dispatch()
  #10 {main}
```

This doesn't seem to be related to my plugins or templates. This isn't a production wiki right now, so unfortunately I don't know when this started.

I found [this thread on the dokuwiki forum](https://forum.dokuwiki.org/d/23024-upgrade-error-error-found-unconstructed-intldateformatter), which suggests that this might be due to a bad PHP configuration. My configured PHP timezone is `Europe/Dublin`, which is a supported timezone, so I'm not sure if that's relevant.

My compose file is here: https://github.com/gserv-me/containers/blob/main/rephasing/wiki/docker-compose.yml

**Comment by gdude2002** [comment]
I can confirm that downgrading to the `oldstable` or `2024-02-06b` tag removes the issue.

**Comment by splitbrain** [comment]
I cannot reproduce this using this docker-compose.yaml:

```yaml
services:
  dokuwiki:
    image: dokuwiki/dokuwiki:stable # other tags: master, <date> or <codename>
    user: "1000:1000" # adjust to your required user id
    restart: unless-stopped
    ports:
      - "8080:8080" # internal port is 8080, map to what you need
    environment:
      PHP_TIMEZONE: Europe/Dublin
      #PHP_MEMORYLIMIT: 256M
      #PHP_UPLOADLIMIT: 128M
    volumes:
      - ./storage:/storage
 ```
