### ISSUE TITLE
Can't stop container in rootless mode

### ISSUE THREAD

**Issue by notalexnot** [dokuwiki/docker#8]
Hey!

I'm using DokuWiki in rootless mode, which works great now, without any file reading/writing problems, but I've encountered that I cannot stop the container without having to use `docker kill` or restarting the Docker daemon. 

If I run `docker stop dokuwiki` I get the error: `Error response from daemon: cannot stop container: dokuwiki: permission denied`. Sadly, this means that I can't update the container without having to forcefully kill it nor use Watchtower with it. 

The container has the usual processes of any container and the users: `root` and `www-data` that other containers I run also have without causing any problems.

I don't seem to be able to get any logs showing errors and the permissions don't look too weird, so I'm not sure where to look,  but I suspect the owner of some process may be at fault.

I'd be glad if you could help me with this, in case it's fixable. Thanks for reading and for this good project! (it's the only wiki I can run with almost zero issues) :)

**Comment by splitbrain** [comment]
what's the exact command you're starting the container with?

**Comment by notalexnot** [comment]
I use `docker compose up -d` and I _don't_ use the flag `user: 1000:1000` in my compose file, since it caused file permission issues

**Comment by splitbrain** [comment]
what's your exact compose file then? and as which user (uid) are you running docker compose?

**Comment by notalexnot** [comment]
This is my docker-compose.yml: 
```
services:
  dokuwiki:
    container_name: dokuwiki
    image: dokuwiki/dokuwiki:stable
    restart: 'unless-stopped'
    networks:
      - default
    #user: "1000:1000"
    ports:
      - "8080:8080"
    environment:
      PHP_TIMEZONE: America/Monterrey
      PUID: 1000
      PGID: 1000

    volumes:
      - ./storage:/storage:rw

networks:
  default:
    external: true
    name: proxynet
```

I'm running the container as my user: `1000` and group: `1000` also.
